version: '3.3'
services:
  db-login:
    container_name: wa2-db-login-pg
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - '<absolute_projectpath>\postgres\data:/var/lib/postgresql/data'
    image: postgres

  db-traveler:
      container_name: wa2-db-traveler-pg
      ports:
        - '5433:5432'
      environment:
        - POSTGRES_PASSWORD=pwd
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - '<absolute_projectpath>\postgres\datatv:/var/lib/postgresql/data'
      image: postgres

  db-ticketCatalogue:
      container_name: wa2-db-ticketCatalogue-pg
      ports:
        - '5434:5432'
      environment:
        - POSTGRES_PASSWORD=pwd
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - '<absolute_projectpath>\postgres\datatc:/var/lib/postgresql/data'
      image: postgres

  db-payment:
    container_name: wa2-db-payment-pg
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_PASSWORD=pwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - '<absolute_projectpath>\postgres\datapy:/var/lib/postgresql/data'
    image: postgres

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      -   kafka-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: '  kafka-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1